apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: jenkins-k8s-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec", "pods/log", "events", "secrets", "services"]
  verbs: ["create", "delete", "get", "list", "patch", "update", "watch"]