apiVersion: apps/v1
kind: Deployment
metadata:
  name: premium-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: premium-app
  template:
    metadata:
      labels:
        app: premium-app
    spec:
      containers:
      - image: deampuleadd/app
        imagePullPolicy: Always
        name: php-fpm
        volumeMounts:
        - mountPath: /var/www/html/.env
          name: env-secret-volume
          subPath: .env
        - mountPath: /var/www/html/public/images
          name: nfs-storage
          subPath: images
      - image: deampuleadd/nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/html/public/images
          name: nfs-storage
          subPath: images
      volumes:
      - name: env-secret-volume
        secret:
          secretName: sealed-env-secret
      - name: nfs-storage
        persistentVolumeClaim:
          claimName: nfs-main-pvc
